/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  src\MotionProfiles.h
 *  model: robotti_V3_hc
 *  expmt: robotti_V3_hc
 *  date:  October 17, 2017
 *  time:  1:03:17 PM
 *  user:  INTO-CPS
 *  from:  20-sim 4.6 Professional Single
 *  build: 4.6.3.7711
 **********************************************************/

/* This file defines the functions necessary for motion profiles
   functions
*/
