/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  src\xxTable2D.c
 *  model: robotti_V3_hc
 *  expmt: robotti_V3_hc
 *  date:  October 17, 2017
 *  time:  1:03:17 PM
 *  user:  INTO-CPS
 *  from:  20-sim 4.6 Professional Single
 *  build: 4.6.3.7711
 **********************************************************/

/* Empty file; no Table2D support needed for this model */

